Repository AY2021S1-CS2103-F10-1/tp, pull requests merged in 2020-11, with the labels that each got.

#206 Fix Id
  src/main/java/seedu/canoe/logic/commands/FindBadStudentsCommand.java
  src/main/java/seedu/canoe/model/student/Id.java
  src/main/java/seedu/canoe/ui/StudentCard.java
  src/test/java/seedu/canoe/logic/commands/FindBadStudentsCommandTest.java
  src/test/java/seedu/canoe/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/canoe/logic/commands/UnmarkAttendanceCommandTest.java
Labels: GUI, severity.Medium, type.Bug

#209 Fix date bugs in datetime parsing, improved error messages
  src/main/java/seedu/canoe/logic/commands/FindStudentTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParser.java
  src/main/java/seedu/canoe/logic/parser/ParserUtil.java
  src/main/java/seedu/canoe/logic/parser/TrainingCommandParser.java
  src/main/java/seedu/canoe/model/student/Student.java
  src/main/java/seedu/canoe/model/training/Training.java
  src/main/java/seedu/canoe/model/util/StudentTrainingSessionUtil.java
  src/main/java/seedu/canoe/ui/ResultDisplay.java
  src/main/java/seedu/canoe/ui/StudentCard.java
  src/test/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParserTest.java
Labels: enhancement, priority.High

#210 Update FindCommand & Parser and Id Stuff
  src/main/java/seedu/canoe/logic/parser/CommonTimeCommandParser.java
  src/main/java/seedu/canoe/logic/parser/FindCommandParser.java
  src/main/java/seedu/canoe/logic/parser/ParserUtil.java
  src/main/java/seedu/canoe/model/student/AcademicYearMatchesPredicate.java
  src/main/java/seedu/canoe/model/student/Id.java
  src/main/java/seedu/canoe/model/student/PhoneMatchesPredicate.java
  src/main/java/seedu/canoe/model/training/Training.java
  src/test/java/seedu/canoe/logic/commands/CommonTimeCommandTest.java
  src/test/java/seedu/canoe/logic/commands/FindCommandTest.java
  src/test/java/seedu/canoe/logic/parser/CanoeCoachParserTest.java
  src/test/java/seedu/canoe/logic/parser/CommonTimeCommandParserTest.java
  src/test/java/seedu/canoe/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/canoe/model/student/AcademicYearMatchesPredicateTest.java
  src/test/java/seedu/canoe/model/student/AllMatchPredicateListTest.java
  src/test/java/seedu/canoe/model/student/PhoneMatchesPredicateTest.java
Labels: enhancement, severity.Medium

#216 Added PPP, assertions, and standardised "!" at the end of error messages.
  docs/UserGuide.md
  docs/team/weiheng.md
  src/main/java/seedu/canoe/commons/core/Messages.java
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
Labels: documentation

#217 Fixes ts-delete duplicate id input, and PPP
  docs/team/sudogene.md
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/test/java/seedu/canoe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommandTest.java
Labels: documentation, type.Bug

#218 Fix UG table bug
  docs/UserGuide.md
Labels: documentation

#221 Update User Guide and PPP
  docs/UserGuide.md
  docs/team/jiadong.md
Labels: documentation

#223 Standardize Handling of Repeated Id Inputs for Parsers & Commands
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/CommandUtil.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/canoe/logic/parser/DeleteStudentFromTrainingCommandParser.java
  src/main/java/seedu/canoe/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/canoe/logic/parser/ParserUtil.java
  src/main/java/seedu/canoe/logic/parser/UnmarkAttendanceCommandParser.java
  src/main/java/seedu/canoe/model/student/Id.java
  src/test/java/seedu/canoe/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommandTest.java
Labels: refactor

#224 Standardize multiple Id messages & Abstract methods to CommandUtil
  src/main/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/CommandUtil.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/FindStudentTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/canoe/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParser.java
  src/main/java/seedu/canoe/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/canoe/logic/parser/UnmarkAttendanceCommandParser.java
  src/test/java/seedu/canoe/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/FindStudentTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/canoe/logic/commands/UnmarkAttendanceCommandTest.java
Labels: refactor, type.Bug

#228 Add tests for Utils and Parser (ts-delete)
  src/test/java/seedu/canoe/logic/commands/CommandUtilTest.java
  src/test/java/seedu/canoe/logic/parser/DeleteStudentFromTrainingCommandParserTest.java
  src/test/java/seedu/canoe/logic/parser/ParserUtilTest.java
Labels: enhancement, refactor

#226 PPP and UG Glossary
  docs/UserGuide.md
  docs/team/kerkpy.md
Labels: documentation

#229 [Andy] Logo, UG, and PPP
  docs/UserGuide.md
  docs/images/canoe-coach-logo.png
  docs/team/sudogene.md
Labels: documentation

#233 Modify UG with Visuals and Graphics
  docs/UserGuide.md
  docs/images/AddStudent.png
  docs/images/CommonTime.png
  docs/images/DeleteStudent.png
  docs/images/EditStudent.png
  docs/images/Find.png
  docs/images/FindTraining.png
  docs/images/GeneralStructure.png
  docs/images/Help.png
  docs/images/MarkAttendance.png
  docs/images/Training.png
  docs/images/Ts-Add.png
  docs/images/Ui.png
  docs/team/jiadong.md
  src/main/java/seedu/canoe/model/training/TrainingMatchesDateTimePredicate.java
  src/test/java/seedu/canoe/logic/commands/FindStudentTrainingCommandTest.java
  src/test/java/seedu/canoe/model/student/DateTimeMatchesPredicateTest.java
  src/test/java/seedu/canoe/model/training/TrainingMatchesDateTimePredicateTest.java
Labels: documentation

#234 [Andy] Bug fix: Id query
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/CommandUtil.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/canoe/logic/parser/DeleteStudentFromTrainingCommandParser.java
  src/main/java/seedu/canoe/logic/parser/FindCommandParser.java
  src/main/java/seedu/canoe/logic/parser/ParserUtil.java
  src/main/java/seedu/canoe/model/student/Id.java
  src/test/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/canoe/logic/commands/CommandUtilTest.java
  src/test/java/seedu/canoe/logic/parser/ParserUtilTest.java
Labels: type.Bug

#235 Update DG and PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/whleee.md
Labels: documentation

#244 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindTrainingPredicatesDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TrainingStudentAttendRS.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/FindTrainingPredicatesDiagram.png
  docs/images/MarkAttendanceActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/TrainingStudentAttendRS.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/team/yejiadong.md
  src/main/java/seedu/canoe/storage/JsonAdaptedAttendance.java
  src/main/java/seedu/canoe/storage/JsonAdaptedStudent.java
  src/test/java/seedu/canoe/storage/JsonAdaptedStudentTest.java
Labels: documentation

#245 Update User Guide and Graphics
  docs/UserGuide.md
  docs/images/AddStudent.png
  docs/images/DeleteStudent.png
  docs/images/EditStudent.png
  src/main/java/seedu/canoe/logic/commands/FindStudentTrainingCommand.java
Labels: documentation
