Repository AY2021S1-CS2103-F10-1/tp, pull requests merged in 2020-10, with the labels that each got.

#54 Modify Documentation of User Guide, Developer Guide, _config.yml and index file
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_config.yml
  docs/index.md
Labels: documentation

#56 Closes #55 Update Ui image
  docs/images/Ui.png
Labels: documentation

#57 Update AboutUs, User Guide, README files
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
Labels: documentation

#58 Update AboutUs Page
  docs/AboutUs.md
Labels: documentation

#59 Update README with CI status
  README.md
  build.gradle
Labels: documentation

#60 Fix Bug in README CI
  README.md
Labels: documentation

#67 Add training schedule container in Student
  src/main/java/seedu/address/model/student/Student.java
Labels: enhancement

#68 [Branch] Add Student Id field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Id.java
  src/main/java/seedu/address/model/student/IdMatchesPredicate.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: enhancement

#71 Training class and TrainingCommands added.
  Could
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java
  src/main/java/seedu/address/logic/commands/TrainingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteTrainingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TrainingCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/student/Id.java
  src/main/java/seedu/address/model/student/Training.java
  src/main/java/seedu/address/model/student/UniqueTrainingList.java
  src/main/java/seedu/address/model/student/exceptions/DuplicateTrainingException.java
  src/main/java/seedu/address/model/student/exceptions/TrainingNotFoundException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TrainingCard.java
  src/main/java/seedu/address/ui/TrainingListPanel.java
  src/main/resources/view/TrainingListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTrainingCommandTest.java
  src/test/java/seedu/address/logic/commands/TrainingCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TrainingBuilder.java
  src/test/java/seedu/address/testutil/TypicalTraining.java
Labels: enhancement

#72 modify student Id to be auto-assigned and unique
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Id.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/student/IdMatchesPredicateTest.java
  src/test/java/seedu/address/model/student/IdTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High

#73 Minor BugFixes, Add PlaceHolders for Training session students, Storage improved.
  src/main/java/seedu/address/logic/commands/TrainingCommand.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueTrainingList.java
  src/main/java/seedu/address/storage/JsonAdaptedTraining.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/main/java/seedu/address/ui/TrainingCard.java
  src/main/java/seedu/address/ui/TrainingListPanel.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
Labels: enhancement

#75 Link trainings to students + Test and Bug Fixes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TrainingCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTraining.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/LocalDateTimeUtil.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TrainingBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: enhancement, priority.High

#74 Find common free time test classes
  src/main/java/seedu/address/logic/commands/CommonTimeCommand.java
  src/main/java/seedu/address/model/student/CommonTimeFinder.java
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommonTimeCommandTest.java
  src/test/java/seedu/address/logic/parser/CommonTimeCommandParserTest.java
  src/test/java/seedu/address/model/student/CommonTimeFinderTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: enhancement

#83 Feature: Add Students to Training Sessions
  docs/images/abdurrahmanfaqihiskandar 2.png
  docs/images/kerkpy 2.jpeg
  docs/images/sudogene 2.jpeg
  docs/images/whleee 2.jpg
  docs/images/yejiadong 2.jpeg
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Training.java
  src/main/java/seedu/address/model/student/UniqueTrainingList.java
  src/main/java/seedu/address/storage/JsonAdaptedTraining.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromTrainingCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTrainingTest.java
  src/test/java/seedu/address/testutil/TypicalTraining.java
Labels: enhancement

#84 Add anyMatch PredicateList for common time use case
  src/main/java/seedu/address/logic/commands/CommonTimeCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CommonTimeCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/student/AllMatchPredicateList.java
  src/main/java/seedu/address/model/student/AnyMatchPredicateList.java
  src/test/java/seedu/address/logic/commands/CommonTimeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommonTimeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/student/AllMatchPredicateListTest.java
Labels: enhancement

#86 Fix Bugs in adding and removal of students to training
  src/main/java/seedu/address/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteStudentFromTrainingCommandParser.java
  src/main/java/seedu/address/model/student/Training.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromTrainingCommandTest.java
Labels: severity.High

#81 Student: Add method to check whether a student is able to attend a training
  src/main/java/seedu/address/model/student/Student.java
Labels: enhancement

#89 Add dismissal time check for add student to training command and include tests for add/delete student to/from training
  src/main/java/seedu/address/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/address/ui/TrainingCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TrainingListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromTrainingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/LocalDateTimeUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
  src/test/java/seedu/address/testutil/TypicalStudentsInTypicalTrainings.java
  src/test/java/seedu/address/testutil/TypicalTraining.java
Labels: enhancement

#91 Edit student tagged to training
  src/main/java/seedu/address/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/TrainingMatchesPredicate.java
  src/main/java/seedu/address/model/student/UniqueTrainingList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/StudentTrainingSessionUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: enhancement

#93 Branch fixes delete training 2
  src/main/java/seedu/address/logic/commands/DeleteTrainingCommand.java
  src/main/java/seedu/address/model/student/Student.java
Labels: type.Bug

#92 BugFix: Unexpected behaviour for AddStudentToTrainingCommand and DeleteStudentFromTrainingCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/commands/AddStudentToTrainingCommandTest.java
Labels: type.Bug

#96 Edit User Guide and README file
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#100 Fix Bugs and Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/CommonTimeCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/CommonTimeCommandParser.java
  src/main/java/seedu/canoe/logic/parser/FindCommandParser.java
  src/main/java/seedu/canoe/model/student/Student.java
Labels: documentation, type.Bug

#102 Fix Bugs and Update User Guide
  docs/UserGuide.md
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/EditCommand.java
  src/main/java/seedu/canoe/model/student/Student.java
Labels: documentation, type.Bug

#103 Fix student comparison and Id increment
  src/main/java/seedu/canoe/logic/commands/AddCommand.java
  src/main/java/seedu/canoe/logic/commands/EditCommand.java
  src/main/java/seedu/canoe/logic/parser/AddCommandParser.java
  src/main/java/seedu/canoe/model/student/Id.java
  src/main/java/seedu/canoe/model/student/Student.java
  src/test/java/seedu/canoe/logic/commands/EditCommandTest.java
  src/test/java/seedu/canoe/model/student/IdTest.java
  src/test/java/seedu/canoe/model/student/StudentTest.java
  src/test/java/seedu/canoe/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/canoe/testutil/TypicalStudents.java
Labels: type.Bug

#104 Updated Training and TrainingCard as per specification.
  docs/images/Ui.png
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/model/student/Training.java
  src/main/java/seedu/canoe/ui/TrainingCard.java
Labels: type.Enhancement

#112 [Closes #110] Modify training command to only allow present and future date and time
  src/main/java/seedu/canoe/logic/commands/TrainingCommand.java
  src/test/java/seedu/canoe/logic/commands/TrainingCommandTest.java
Labels: enhancement

#113 Create Attend Class
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/EditCommand.java
  src/main/java/seedu/canoe/model/student/Attend.java
  src/main/java/seedu/canoe/model/student/Student.java
  src/main/java/seedu/canoe/model/student/Training.java
  src/main/java/seedu/canoe/model/student/TrainingMatchesPredicate.java
  src/main/java/seedu/canoe/model/util/SampleDataUtil.java
  src/main/java/seedu/canoe/model/util/StudentTrainingSessionUtil.java
  src/main/java/seedu/canoe/storage/JsonAdaptedStudent.java
  src/main/java/seedu/canoe/ui/StudentCard.java
  src/test/java/seedu/canoe/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommandTest.java
  src/test/java/seedu/canoe/model/student/StudentTest.java
  src/test/java/seedu/canoe/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/canoe/testutil/StudentBuilder.java
Labels: enhancement

#114 Add find-training command to filter one student and display all his/her trainings
  build.gradle
  src/main/java/seedu/canoe/commons/core/Messages.java
  src/main/java/seedu/canoe/logic/commands/DeleteTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/FindStudentTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/CanoeCoachParser.java
  src/main/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParser.java
  src/main/java/seedu/canoe/model/student/Training.java
  src/main/java/seedu/canoe/model/student/TrainingMatchesIdPredicate.java
  src/main/java/seedu/canoe/ui/StudentCard.java
Labels: enhancement

#116 Add All Students to Training
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/canoe/commons/core/Messages.java
  src/main/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/CommonTimeCommand.java
  src/main/java/seedu/canoe/logic/parser/AddAllStudentCommandParser.java
  src/main/java/seedu/canoe/logic/parser/CanoeCoachParser.java
  src/main/java/seedu/canoe/logic/parser/CommonTimeCommandParser.java
  src/main/java/seedu/canoe/model/student/Training.java
  src/test/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/CommonTimeCommandTest.java
  src/test/java/seedu/canoe/testutil/LocalDateTimeUtil.java
  src/test/java/seedu/canoe/testutil/TypicalTraining.java
Labels: enhancement

#119 Branch attend command tests
  src/test/java/seedu/canoe/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/canoe/testutil/TypicalStudents.java
Labels: enhancement

#120 V1.3 ts addall
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/AddAllStudentCommandParser.java
  src/main/java/seedu/canoe/logic/parser/CanoeCoachParser.java
  src/main/java/seedu/canoe/model/student/Training.java
  src/test/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/testutil/LocalDateTimeUtil.java
  src/test/java/seedu/canoe/testutil/TypicalTraining.java
Labels: enhancement

#122 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindTrainingActivityDiagram.puml
  docs/diagrams/FindTrainingSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TrainingMatchesIdPredicate.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FindTrainingActivityDiagram.png
  docs/images/FindTrainingSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/TrainingMatchesIdPredicate.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/canoe/logic/commands/CommonTimeCommand.java
  src/main/java/seedu/canoe/model/student/Student.java
  src/main/java/seedu/canoe/model/student/Training.java
Labels: documentation

#125 Update list and training commands to un-filter training panel
  src/main/java/seedu/canoe/logic/commands/ListCommand.java
  src/main/java/seedu/canoe/logic/commands/TrainingCommand.java
Labels: enhancement

#123 Merging Attendance
  src/main/java/seedu/canoe/commons/core/Messages.java
  src/main/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/AddCommand.java
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/CommonTimeCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/EditCommand.java
  src/main/java/seedu/canoe/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/canoe/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/canoe/logic/parser/CanoeCoachParser.java
  src/main/java/seedu/canoe/logic/parser/CommonTimeCommandParser.java
  src/main/java/seedu/canoe/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/canoe/model/student/Attend.java
  src/main/java/seedu/canoe/model/student/Student.java
  src/main/java/seedu/canoe/model/student/Training.java
  src/main/java/seedu/canoe/model/student/TrainingMatchesPredicate.java
  src/main/java/seedu/canoe/model/util/SampleDataUtil.java
  src/main/java/seedu/canoe/model/util/StudentTrainingSessionUtil.java
  src/main/java/seedu/canoe/storage/JsonAdaptedAttend.java
  src/main/java/seedu/canoe/storage/JsonAdaptedStudent.java
  src/main/java/seedu/canoe/storage/JsonCanoeCoachStorage.java
  src/main/java/seedu/canoe/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/canoe/logic/LogicManagerTest.java
  src/test/java/seedu/canoe/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/canoe/logic/parser/CanoeCoachParserTest.java
  src/test/java/seedu/canoe/logic/parser/MarkAttendanceCommandParserTest.java
  src/test/java/seedu/canoe/model/student/StudentTest.java
  src/test/java/seedu/canoe/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/canoe/testutil/StudentBuilder.java
  src/test/java/seedu/canoe/testutil/TypicalStudents.java
Labels: enhancement

#127 Update DG design details for ts-addall
  docs/DeveloperGuide.md
  docs/diagrams/AddAllStudentToTrainingActivityDiagram.puml
  docs/diagrams/AddAllStudentToTrainingSequenceDiagram.puml
  docs/images/AddAllStudentToTrainingActivityDiagram.png
  docs/images/AddAllStudentToTrainingSequenceDiagram.png
Labels: documentation

#130 Add tests for find-training command and refactor existing test cases
  src/main/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/FindStudentTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParser.java
  src/test/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/FindStudentTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParserTest.java
  src/test/java/seedu/canoe/model/student/StudentTest.java
  src/test/java/seedu/canoe/model/student/TrainingMatchesIdPredicateTest.java
  src/test/java/seedu/canoe/testutil/LocalDateTimeUtil.java
  src/test/java/seedu/canoe/testutil/TypicalIndexes.java
  src/test/java/seedu/canoe/testutil/TypicalStudentsInTypicalTrainings.java
Labels: enhancement

#129 Update DG for ts-add
  docs/DeveloperGuide.md
  docs/diagrams/AddStudentToTrainingActivityDiagram.puml
  docs/diagrams/AddStudentToTrainingSequenceDiagram.puml
  docs/images/AddStudentToTrainingActivityDiagram.png
  docs/images/AddStudentToTrainingSequenceDiagram.png
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/test/java/seedu/canoe/logic/commands/ClearCommandTest.java
Labels: documentation

#142 Modified Add/Delete Student from Training to use unique Ids
  src/main/java/seedu/canoe/MainApp.java
  src/main/java/seedu/canoe/commons/core/index/Index.java
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/test/java/seedu/canoe/logic/commands/AddAllStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/AddStudentToTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/ClearCommandTest.java
  src/test/java/seedu/canoe/logic/commands/CommandTestUtil.java
  src/test/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/commands/FindStudentTrainingCommandTest.java
  src/test/java/seedu/canoe/testutil/LocalDateTimeUtil.java
  src/test/java/seedu/canoe/testutil/TypicalIndexes.java
  src/test/java/seedu/canoe/testutil/TypicalStudentsInTypicalTrainings.java
Labels: enhancement

#144 Update student GUI to support both past and present training display with colour coding
  src/main/java/seedu/canoe/model/student/Attendance.java
  src/main/java/seedu/canoe/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StudentListCard.fxml
Labels: enhancement

#145 Andy code quality ts delete
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/model/student/Id.java
  src/test/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommandTest.java
  src/test/java/seedu/canoe/model/student/IdTest.java
Labels: enhancement

#146 Add ability to find training by datetime
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/FindStudentTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/CliSyntax.java
  src/main/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParser.java
  src/main/java/seedu/canoe/model/student/DateTimeMatchesPredicate.java
  src/main/java/seedu/canoe/model/training/TrainingMatchesDateTimePredicate.java
  src/test/java/seedu/canoe/logic/commands/FindStudentTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParserTest.java
  src/test/java/seedu/canoe/model/student/DateTimeMatchesPredicateTest.java
  src/test/java/seedu/canoe/model/training/TrainingMatchesDateTimePredicateTest.java
Labels: enhancement

#147 Slight upgrade to ts-add code quality by using comments.
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
Labels: documentation

#153 Andy docs n stuffs
  docs/UserGuide.md
  src/main/java/seedu/canoe/model/student/Student.java
  src/main/java/seedu/canoe/model/tag/Tag.java
  src/main/java/seedu/canoe/model/util/SampleDataUtil.java
  src/test/java/seedu/canoe/logic/commands/FindBadStudentsCommandTest.java
Labels: documentation

#155 Fix Bug in Find Training Command
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParser.java
  src/main/java/seedu/canoe/model/student/IdMatchesPredicate.java
  src/main/java/seedu/canoe/model/training/Training.java
  src/main/java/seedu/canoe/model/training/TrainingMatchesIdPredicate.java
  src/test/java/seedu/canoe/logic/commands/FindStudentTrainingCommandTest.java
  src/test/java/seedu/canoe/logic/parser/FindStudentTrainingCommandParserTest.java
  src/test/java/seedu/canoe/model/training/TrainingMatchesIdPredicateTest.java
Labels: type.Bug

#154 Update Userguide, Ui.png and Sample Data
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/canoe/model/student/Student.java
  src/main/java/seedu/canoe/model/util/SampleDataUtil.java
Labels: documentation, enhancement

#150 Improved code-quality for ts-add
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
Labels: enhancement

#157 Fix Ui and dismisal time bugs and update User Guide
  docs/UserGuide.md
  src/main/java/seedu/canoe/model/student/Student.java
  src/main/java/seedu/canoe/model/util/SampleDataUtil.java
  src/main/java/seedu/canoe/model/util/StudentTrainingSessionUtil.java
  src/main/java/seedu/canoe/ui/TrainingCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/StudentListPanel.fxml
  src/main/resources/view/TrainingListCard.fxml
Labels: documentation, enhancement, type.Bug

#158 Fix filtering bugs
  docs/UserGuide.md
  src/main/java/seedu/canoe/logic/commands/AddStudentToTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteStudentFromTrainingCommand.java
  src/main/java/seedu/canoe/logic/commands/DeleteTrainingCommand.java
Labels: enhancement

#159 Update UG and add assertion
  docs/UserGuide.md
  src/main/java/seedu/canoe/model/student/Student.java
Labels: documentation, enhancement

#161 Andy docs n stuffs
  docs/diagrams/AddAllStudentToTrainingSequenceDiagram.puml
  docs/images/AddAllStudentToTrainingSequenceDiagram.png
  src/main/java/seedu/canoe/ui/HelpWindow.java
Labels: documentation

#162 Update version number of MainApp
  src/main/java/seedu/canoe/MainApp.java
Labels: priority.Low
